# Generated by Django 3.2.4 on 2021-07-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairpun',
            name='exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hairpun',
            name='link',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
    ]
