# Generated by Django 3.2.4 on 2021-07-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210706_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairpun',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
