# Generated by Django 3.2.4 on 2021-07-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_hairpun_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('thoughts', models.CharField(max_length=250)),
                ('hairpun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hairpun')),
            ],
        ),
    ]
